### PR TITLE
Sketch out group's consensus regarding markdown

### PR DESCRIPTION
**Pull request by bassosimone**
This edit to the README.md clarifies the process with which we're going to publish future specifications in their final form for developer's consumption, and it also mentions how to handle existing proposals documents.

### CODE REVIEW

**Comment by bassosimone** [comment]
@blanu should I also create a draft template in markdown and refer to it from the README.md?

**Comment by vivivibo** [comment]
@bassosimone Thank you for this PR. Please feel free to add a draft template in markdown.

**Comment by bassosimone** [comment]
@vivivibo I think the template in markdown we can do later.

**Comment by vivivibo** [comment]
> @vivivibo I think the template in markdown we can do later.

Sure!
LGTM, Thank you.

**Pull request merged**
